### ISSUE TITLE
Issue while running

### ISSUE THREAD

**Issue by Greite** [piratedv/gbook-py#4]
Hi, 
i'm trying to run your application but i'm still having this error all the times. I'm not familiar with python. Sorry if this is a obvious error.

`Traceback (most recent call last):
  File "gbook.py", line 2, in <module>
    from facebookbot import FacebookBot
  File "<path>/gbook-py/facebookbot.py", line 4, in <module>
    from locators import LoginPageLocators, PostToGroupsLocators
ImportError: No module named locators`

**Comment by piratedv** [comment]
There should be a folder named "locators" in your main directory. Send the structure of the directory here or upload your code so I can debug it for you.

**Comment by piratedv** [comment]
Create a __init__.py file inside the locators folder.

**Comment by Greite** [comment]
What did i put in the init.py file ?

**Comment by piratedv** [comment]
Pushed new files and reordered the directory structure.
